### Endpoint de teste
GET http://localhost:3003/ping

### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Laura",
    "email": "laura@gmail.com",
    "password": "Laura123"
}